/*
   This file was generated automatically by the Mojo IDE version B1.3.5.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module adder_28 (
    input [7:0] alufn,
    input [7:0] a,
    input [7:0] b,
    output reg [7:0] sum1,
    output reg z,
    output reg v,
    output reg n
  );
  
  
  
  reg [8:0] sum;
  
  reg xb;
  
  always @* begin
    
    case (alufn[6+1-:2])
      2'h2: begin
        sum = a * b;
      end
      2'h1: begin
        sum = a - (a / b * b);
      end
      default: begin
        
        case (alufn[0+0-:1])
          1'h0: begin
            sum = a + b;
            xb = b[7+0-:1];
          end
          1'h1: begin
            sum = a - b;
            xb = ~b[7+0-:1];
          end
          default: begin
            sum = a + b;
            xb = b[7+0-:1];
          end
        endcase
      end
    endcase
    sum1 = sum[0+7-:8];
    v = (a[7+0-:1] & xb & (~sum[7+0-:1])) | ((~a[7+0-:1]) & (~xb) & sum[7+0-:1]);
    n = sum[7+0-:1];
    z = (~|sum[0+7-:8]);
  end
endmodule
