/*
   This file was generated automatically by the Mojo IDE version B1.3.5.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module boolean_26 (
    input [7:0] a,
    input [7:0] b,
    input [5:0] alufn,
    output reg [7:0] bool
  );
  
  
  
  integer i;
  
  always @* begin
    
    case (alufn[0+3-:4])
      4'h8: begin
        for (i = 1'h0; i < 4'h8; i = i + 1) begin
          if (a[(i)*1+0-:1] == 1'h1 && b[(i)*1+0-:1] == 1'h1) begin
            bool[(i)*1+0-:1] = 1'h1;
          end else begin
            bool[(i)*1+0-:1] = 1'h0;
          end
        end
      end
      4'he: begin
        for (i = 1'h0; i < 4'h8; i = i + 1) begin
          if (a[(i)*1+0-:1] == 1'h1 || b[(i)*1+0-:1] == 1'h1) begin
            bool[(i)*1+0-:1] = 1'h1;
          end else begin
            bool[(i)*1+0-:1] = 1'h0;
          end
        end
      end
      4'h6: begin
        for (i = 1'h0; i < 4'h8; i = i + 1) begin
          if (a[(i)*1+0-:1] == b[(i)*1+0-:1]) begin
            bool[(i)*1+0-:1] = 1'h0;
          end else begin
            bool[(i)*1+0-:1] = 1'h1;
          end
        end
      end
      4'ha: begin
        for (i = 1'h0; i < 4'h8; i = i + 1) begin
          bool[(i)*1+0-:1] = a[(i)*1+0-:1];
        end
      end
      default: begin
        bool = 8'h00;
      end
    endcase
  end
endmodule
