/*
   This file was generated automatically by the Mojo IDE version B1.3.5.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module decimal_counter_24 (
    input clk,
    input rst,
    input inc,
    output reg ovf,
    output reg [3:0] value,
    output reg [3:0] count
  );
  
  
  
  reg [3:0] M_val_d, M_val_q = 4'h9;
  reg [3:0] M_counter_d, M_counter_q = 4'ha;
  
  always @* begin
    M_val_d = M_val_q;
    M_counter_d = M_counter_q;
    
    count = M_counter_q;
    value = M_val_q;
    ovf = M_val_q == 1'h0 && inc;
    if (inc) begin
      if (M_val_q == 1'h0) begin
        M_val_d = 4'h9;
        M_counter_d = M_counter_q - 1'h1;
      end else begin
        M_val_d = M_val_q - 1'h1;
      end
    end
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_val_q <= 4'h9;
      M_counter_q <= 4'ha;
    end else begin
      M_val_q <= M_val_d;
      M_counter_q <= M_counter_d;
    end
  end
  
endmodule
