/*
   This file was generated automatically by the Mojo IDE version B1.3.5.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

/*
   Parameters:
     DIGITS = 2
*/
module multi_dec_ctr_10 (
    input clk,
    input rst,
    input inc,
    output reg [7:0] digits,
    output reg [7:0] timer
  );
  
  localparam DIGITS = 2'h2;
  
  
  wire [(2'h2+0)-1:0] M_dctr_ovf;
  wire [(2'h2+0)*4-1:0] M_dctr_value;
  wire [(2'h2+0)*4-1:0] M_dctr_count;
  reg [(2'h2+0)-1:0] M_dctr_inc;
  
  genvar GEN_dctr0;
  generate
  for (GEN_dctr0=0;GEN_dctr0<2'h2;GEN_dctr0=GEN_dctr0+1) begin: dctr_gen_0
    decimal_counter_24 dctr (
      .clk(clk),
      .rst(rst),
      .inc(M_dctr_inc[GEN_dctr0*(1)+(1)-1-:(1)]),
      .ovf(M_dctr_ovf[GEN_dctr0*(1)+(1)-1-:(1)]),
      .value(M_dctr_value[GEN_dctr0*(3'h4)+(3'h4)-1-:(3'h4)]),
      .count(M_dctr_count[GEN_dctr0*(3'h4)+(3'h4)-1-:(3'h4)])
    );
  end
  endgenerate
  
  always @* begin
    timer = M_dctr_count;
    M_dctr_inc[0+0-:1] = inc;
    digits = M_dctr_value;
    M_dctr_inc[1+0-:1] = M_dctr_ovf[0+0-:1];
  end
endmodule
